title: "Entre Sonhos"
description: "Entre Sonhos – blog de escrita, bastidores de livros e deambulações criativas."
url: "https://entre1000sonhos.pt"

author: "Vasco Belo Pereira"

instagram: "https://www.instagram.com/blog_entre_sonhos"
substack: "https://entresonhos.substack.com"

lang: "pt-PT"
theme: minima

header_pages:
  - index.md
  - livros.md
  - recursos.md
  - [Entre Sonhos]({{ site.substack }})
  - sobre.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/
