title: "Entre Sonhos"
description: "Entre Sonhos â€“ o site do escritor Vasco Belo Pereira."
url: "https://entre1000sonhos.pt"

author: "Vasco Belo Pereira"

instagram: "https://www.instagram.com/vasco_entre_sonhos"
substack: "https://entresonhos.substack.com"

lang: "pt-PT"
theme: minima

header_pages:
  - index.md
  - projetos.md
  - recursos.md
  - blog.md
  - sobre.md
  - editoras/index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/
